# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x11vehicle.telemetry\"S\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\tspeed_kmh\x18\x03 \x01(\x02\x12\x0f\n\x07heading\x18\x04 \x01(\x02\"\x94\x01\n\x0c\x42\x61tteryState\x12\x17\n\x0fstate_of_charge\x18\x01 \x01(\x02\x12\x0f\n\x07voltage\x18\x02 \x01(\x02\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x14\n\x0c\x63urrent_draw\x18\x04 \x01(\x02\x12/\n\x06health\x18\x05 \x01(\x0e\x32\x1f.vehicle.telemetry.HealthStatus\"q\n\x0fPowertrainState\x12\x11\n\tmotor_rpm\x18\x01 \x01(\x05\x12\x12\n\nmotor_temp\x18\x02 \x01(\x02\x12\x19\n\x11throttle_position\x18\x03 \x01(\x02\x12\x1c\n\x14regen_braking_active\x18\x04 \x01(\x08\"v\n\x0e\x44iagnosticCode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12-\n\x08severity\x18\x02 \x01(\x0e\x32\x1b.vehicle.telemetry.Severity\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nfirst_seen\x18\x04 \x01(\x03\"\xac\x02\n\x0eTelemetryEvent\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12.\n\x05state\x18\x03 \x01(\x0e\x32\x1f.vehicle.telemetry.VehicleState\x12(\n\x03gps\x18\x04 \x01(\x0b\x32\x1b.vehicle.telemetry.Location\x12\x36\n\npowertrain\x18\x05 \x01(\x0b\x32\".vehicle.telemetry.PowertrainState\x12\x30\n\x07\x62\x61ttery\x18\x06 \x01(\x0b\x32\x1f.vehicle.telemetry.BatteryState\x12/\n\x04\x64tcs\x18\x07 \x03(\x0b\x32!.vehicle.telemetry.DiagnosticCode*8\n\x0cHealthStatus\x12\x0b\n\x07HEALTHY\x10\x00\x12\r\n\tDEGRADING\x10\x01\x12\x0c\n\x08\x43RITICAL\x10\x02*8\n\x08Severity\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\x15\n\x11\x43RITICAL_SEVERITY\x10\x02*5\n\x0cVehicleState\x12\n\n\x06PARKED\x10\x00\x12\x0b\n\x07\x44RIVING\x10\x01\x12\x0c\n\x08\x43HARGING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSTATUS']._serialized_start=812
  _globals['_HEALTHSTATUS']._serialized_end=868
  _globals['_SEVERITY']._serialized_start=870
  _globals['_SEVERITY']._serialized_end=926
  _globals['_VEHICLESTATE']._serialized_start=928
  _globals['_VEHICLESTATE']._serialized_end=981
  _globals['_LOCATION']._serialized_start=38
  _globals['_LOCATION']._serialized_end=121
  _globals['_BATTERYSTATE']._serialized_start=124
  _globals['_BATTERYSTATE']._serialized_end=272
  _globals['_POWERTRAINSTATE']._serialized_start=274
  _globals['_POWERTRAINSTATE']._serialized_end=387
  _globals['_DIAGNOSTICCODE']._serialized_start=389
  _globals['_DIAGNOSTICCODE']._serialized_end=507
  _globals['_TELEMETRYEVENT']._serialized_start=510
  _globals['_TELEMETRYEVENT']._serialized_end=810
# @@protoc_insertion_point(module_scope)
